name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# Refer: https://laravel-news.com/laravel-github-actions
jobs:
  phpunit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2

    services:
      # Refer: https://docs.github.com/en/actions/using-containerized-services/creating-redis-service-containers

      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: abc.xyz
          MYSQL_DATABASE: short_news
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Prepare Laravel Application
        run: |
          composer install --no-scripts
          cp .env.ci .env
          php artisan key:generate
          php artisan migrate --database=test --seed --seeder=InitialDataSeeder

      - name: Run Testsuite
        run: |
          vendor/bin/phpunit tests/
